// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-KM3ozfY_ZUZfZgHAuCyo87U3tJlFMLQ',
    appId: '1:8232328279:web:5d9f5fd27ca2d1ae22d712',
    messagingSenderId: '8232328279',
    projectId: 'kidtech',
    authDomain: 'kidtech.firebaseapp.com',
    storageBucket: 'kidtech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxNZlqxsqout36iRtpxqlNae8gPYNAxs',
    appId: '1:8232328279:android:cd909193844561d122d712',
    messagingSenderId: '8232328279',
    projectId: 'kidtech',
    storageBucket: 'kidtech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxb82RDSoYhwqqnY4nUfqbDQLubgq1sI',
    appId: '1:8232328279:ios:b2c7fb7339ae936b22d712',
    messagingSenderId: '8232328279',
    projectId: 'kidtech',
    storageBucket: 'kidtech.firebasestorage.app',
    iosBundleId: 'com.tuit.texnobilim.texnoBilim',
  );
}
